constants:
  job_running_minutes_interval: 60
  threshold_alert_drop_one_day: -10
  threshold_alert_drop_one_hour: -3
urls:
  url_last_price_coin_binance_api: https://api.binance.com/api/v3/ticker/price?symbol={COIN_PAIR_SYMBOL}
  url_ticker_coin_last_day_binance_api: https://api.binance.com/api/v3/ticker/24hr?symbol={COIN_PAIR_SYMBOL}
  url_candles_coin_time_interval: https://api.binance.com/api/v3/klines?symbol={COIN_PAIR_SYMBOL}&interval={TIME_INTERVAL}&limit={TIME_LIMIT}
parameters:
  coin_pairs:
    - BTCBRL
    - ETHBRL
    - ADABRL
    - DOTBRL
  format_datetime: '%H:%M:%S %d/%m/%Y'
  timezone: America/Sao_Paulo